// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlaylistAppEF.Data;

#nullable disable

namespace PlaylistAppEF.Migrations
{
    [DbContext(typeof(PlaylistContext))]
    partial class PlaylistContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("PlaylistAppEF.Models.Chanson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AjouteLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Annee")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artiste")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("DureeSecondes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Note")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Artiste")
                        .HasDatabaseName("IX_Chansons_Artiste");

                    b.HasIndex("Genre")
                        .HasDatabaseName("IX_Chansons_Genre");

                    b.ToTable("Chansons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "A Night at the Opera",
                            Annee = 1975,
                            Artiste = "Queen",
                            DureeSecondes = 354,
                            Genre = "Rock",
                            Note = 5,
                            Titre = "Bohemian Rhapsody"
                        },
                        new
                        {
                            Id = 2,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Hotel California",
                            Annee = 1977,
                            Artiste = "Eagles",
                            DureeSecondes = 391,
                            Genre = "Rock",
                            Note = 5,
                            Titre = "Hotel California"
                        },
                        new
                        {
                            Id = 3,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "After Hours",
                            Annee = 2019,
                            Artiste = "The Weeknd",
                            DureeSecondes = 200,
                            Genre = "Pop",
                            Note = 4,
                            Titre = "Blinding Lights"
                        },
                        new
                        {
                            Id = 4,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "÷ (Divide)",
                            Annee = 2017,
                            Artiste = "Ed Sheeran",
                            DureeSecondes = 234,
                            Genre = "Pop",
                            Note = 4,
                            Titre = "Shape of You"
                        },
                        new
                        {
                            Id = 5,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "8 Mile Soundtrack",
                            Annee = 2002,
                            Artiste = "Eminem",
                            DureeSecondes = 326,
                            Genre = "Rap",
                            Note = 5,
                            Titre = "Lose Yourself"
                        },
                        new
                        {
                            Id = 6,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Scorpion",
                            Annee = 2018,
                            Artiste = "Drake",
                            DureeSecondes = 198,
                            Genre = "Rap",
                            Note = 4,
                            Titre = "God's Plan"
                        },
                        new
                        {
                            Id = 7,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Nevermind",
                            Annee = 1991,
                            Artiste = "Nirvana",
                            DureeSecondes = 301,
                            Genre = "Rock",
                            Note = 5,
                            Titre = "Smells Like Teen Spirit"
                        },
                        new
                        {
                            Id = 8,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "21",
                            Annee = 2010,
                            Artiste = "Adele",
                            DureeSecondes = 228,
                            Genre = "Soul",
                            Note = 5,
                            Titre = "Rolling in the Deep"
                        },
                        new
                        {
                            Id = 9,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Thriller",
                            Annee = 1982,
                            Artiste = "Michael Jackson",
                            DureeSecondes = 294,
                            Genre = "Pop",
                            Note = 5,
                            Titre = "Billie Jean"
                        },
                        new
                        {
                            Id = 10,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Discovery",
                            Annee = 2000,
                            Artiste = "Daft Punk",
                            DureeSecondes = 321,
                            Genre = "Électro",
                            Note = 5,
                            Titre = "One More Time"
                        },
                        new
                        {
                            Id = 11,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Random Access Memories",
                            Annee = 2013,
                            Artiste = "Daft Punk",
                            DureeSecondes = 369,
                            Genre = "Électro",
                            Note = 4,
                            Titre = "Get Lucky"
                        },
                        new
                        {
                            Id = 12,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Album = "Saturday Night Fever",
                            Annee = 1977,
                            Artiste = "Bee Gees",
                            DureeSecondes = 245,
                            Genre = "Disco",
                            Note = 4,
                            Titre = "Stayin' Alive"
                        });
                });

            modelBuilder.Entity("PlaylistAppEF.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreeLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifieLe")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique()
                        .HasDatabaseName("IX_Playlists_Nom");

                    b.ToTable("Playlists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreeLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Les incontournables du rock",
                            ModifieLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nom = "Rock Classics"
                        },
                        new
                        {
                            Id = 2,
                            CreeLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Meilleures chansons pop",
                            ModifieLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nom = "Pop Hits 2010-2020"
                        },
                        new
                        {
                            Id = 3,
                            CreeLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Pour danser toute la nuit",
                            ModifieLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nom = "Électro Vibes"
                        });
                });

            modelBuilder.Entity("PlaylistAppEF.Models.PlaylistChanson", b =>
                {
                    b.Property<int>("PlaylistId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChansonId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AjouteLe")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlaylistId", "ChansonId");

                    b.HasIndex("ChansonId");

                    b.ToTable("PlaylistChansons");

                    b.HasData(
                        new
                        {
                            PlaylistId = 1,
                            ChansonId = 1,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 1
                        },
                        new
                        {
                            PlaylistId = 1,
                            ChansonId = 2,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 2
                        },
                        new
                        {
                            PlaylistId = 1,
                            ChansonId = 7,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 3
                        },
                        new
                        {
                            PlaylistId = 2,
                            ChansonId = 3,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 1
                        },
                        new
                        {
                            PlaylistId = 2,
                            ChansonId = 4,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 2
                        },
                        new
                        {
                            PlaylistId = 2,
                            ChansonId = 8,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 3
                        },
                        new
                        {
                            PlaylistId = 2,
                            ChansonId = 9,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 4
                        },
                        new
                        {
                            PlaylistId = 3,
                            ChansonId = 10,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 1
                        },
                        new
                        {
                            PlaylistId = 3,
                            ChansonId = 11,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 2
                        },
                        new
                        {
                            PlaylistId = 3,
                            ChansonId = 12,
                            AjouteLe = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Position = 3
                        });
                });

            modelBuilder.Entity("PlaylistAppEF.Models.PlaylistChanson", b =>
                {
                    b.HasOne("PlaylistAppEF.Models.Chanson", "Chanson")
                        .WithMany("PlaylistChansons")
                        .HasForeignKey("ChansonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PlaylistAppEF.Models.Playlist", "Playlist")
                        .WithMany("PlaylistChansons")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chanson");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("PlaylistAppEF.Models.Chanson", b =>
                {
                    b.Navigation("PlaylistChansons");
                });

            modelBuilder.Entity("PlaylistAppEF.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistChansons");
                });
#pragma warning restore 612, 618
        }
    }
}
